### ISSUE TITLE
$steam->validate()  always return false

### ISSUE THREAD

**Issue by radiumx3** [invisnik/laravel-steam-auth#10]
@invisnik As the title say, everything is in place, after signin in in steam page, I pass on the else case as if the login's fail.

**Comment by invisnik** [comment]
In the config ```'redirect_url'``` must been controller route where checks ```$steam->validate();```

**Comment by radiumx3** [comment]
Thanks; this should seriously be documented tho', makes people trying to figure out how this should work and loosing time ...

**Comment by radiumx3** [comment]
any documentation planned about all this lib functions ?

**Comment by invisnik** [comment]
I dont know. Maybe :)
