### ISSUE TITLE
Client error: `POST https://steamcommunity.com/openid/login` resulted in a `403 Forbidden` 

### ISSUE THREAD

**Issue by RaV3NS** [invisnik/laravel-steam-auth#108]
Got this error on my host:

```
GuzzleHttp \ Exception \ ClientException (403)
Client error: `POST https://steamcommunity.com/openid/login` resulted in a `403 Forbidden` response: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "ht (truncated...)
```

I tried on http/https, with or without paid domain - same error. 
ON LOCALHOST IT WORKS!!
But on server i have this problem. My friend tried to upload all project files on his host and it works, but whenever i try to do it on my host, everytime got this issue, even with different steam api keys. I tried different hosts.
Is this magic ? Or ban ? WTF?

**Comment by andreich1980** [comment]
Seems like steam banned your website IP.

**Comment by cashalotkzn** [comment]
+ help me, i have same problem

**Comment by andreich1980** [comment]
@cashalotkzn I had to use proxy to access steam :(

**Comment by cashalotkzn** [comment]
@andreich1980 как ты это решил? Прокси в газзл засунул?

**Comment by RaV3NS** [comment]
> @andreich1980 как ты это решил? Прокси в газзл засунул?

Это бан от стима. Только не понятно на чем он основан.
Для примера: Я использую хост beget, я регистрирую новый бегет -> заливаю сайт -> та же проблема. То же самое если я использую другие хосты.
При этом регает тот же бегет мой товарищ, я заливаю проект -> Все работает.
Не знаю на каком этапе оно блокирует домен, там фактически магия, но думаю если кто то зарегает хостинг и даст тебе креды - должно помочь.
