### ISSUE TITLE
Move config/steam-auth.php info in config/services.php

### ISSUE THREAD

**Issue by 42antoine** [invisnik/laravel-steam-auth#16]
Could you move config/steam-auth.php info in config/services.php like OAuth package https://github.com/laravel/socialite ?

**Comment by Gummibeer** [comment]
@42antoine I'm totaly on your side - the only problem would be that it is a breaking change and it's not possible, with laravel ways, to append to a config - so the devs have to insert it by there own. But yes, it would be the better place!

**Comment by Gummibeer** [comment]
@invisnik Why won't fix?
