### ISSUE TITLE
https is not functioning

### ISSUE THREAD

**Issue by ajanes3** [invisnik/laravel-steam-auth#22]
If the site is https, then the openid.realm must reflect that. Otherwise the login fails. There is the start of code to correct this, but it is not correct.

Add to config file:
`'https' => true,`

However, that still did not fix it.

In SteamAuth.php line ~131 change the following...
`'openid.realm' => \Config::get('steam-auth.https') ? 'https' : 'http' . '://' . $this->request->server('HTTP_HOST'),`

...to this...
`'openid.realm' => \Config::get('steam-auth.https') ? 'https' . '://' . $this->request->server('HTTP_HOST') : 'http' . '://' . $this->request->server('HTTP_HOST'),`

**Comment by ajanes3** [comment]
Or, do a better job than I did at fixing it. But that code does work. :P

**Comment by ajanes3** [comment]
One more comment. Yes it does fix it.

**Comment by Gummibeer** [comment]
Meaned is this line: https://github.com/invisnik/laravel-steam-auth/blob/master/src/SteamAuth.php#L131
and fixed it look's like this: https://github.com/invisnik/laravel-steam-auth/pull/23/files

@ajanes3: don't duplicate too much code ;)

**Comment by Gummibeer** [comment]
@invisnik also solved after PR #23 is merged!?

**Comment by invisnik** [comment]
@Gummibeer i guess so :)
