### ISSUE TITLE
Ошибка метода 'empty'

### ISSUE THREAD

**Issue by Appletinee** [invisnik/laravel-steam-auth#3]
В PHP 5.5 есть некое ограничение при использовании 'empty()' - в качестве аргумента нельзя использовать другой метод.
Поэтому " !empty($this->request->server('HTTPS')) " (SteamAuth.php:119) будет выдавать ошибку. Вынеси аргумент в отдельную переменную и подставляй ее.

**Comment by invisnik** [comment]
Спасибо за замечание, исправил.
