### ISSUE TITLE
Missing argument in SteamAuth::__construct()

### ISSUE THREAD

**Issue by KAMAELUA** [invisnik/laravel-steam-auth#38]
Hello, I think that you should fix this small issue.

> Type error: Argument 1 passed to Invisnik\LaravelSteamAuth\SteamAuth::__construct() must be an instance of Illuminate\Http\Request

You have created constructor for SteamAuth:
```php
public function __construct(Request $request)
{
    ...
}
```

but when you `register()` it in `SteamServiceProvider` you don't pass `Request $request` to it: 

```php
public function register()
{
    $this->app['steamauth'] = $this->app->share(
        function () {
            return new SteamAuth();
        }
    );
}
```

In this case when I trying to generate PHPDoc via barryvdh/laravel-ide-helper it throws this exception.

**Comment by timetorock** [comment]
#49 Here is Pull request with normal fix.

**Comment by timetorock** [comment]
@KAMAELUA check this pull request #49
