### ISSUE TITLE
Upgrade laravel 5.2 -> 5.3

### ISSUE THREAD

**Issue by ImChip** [invisnik/laravel-steam-auth#39]
Hello ,

I recently decided to update my project laravel 5.2 to version 5.3
However everything worked except this package

I have an error

> Object of class Invisnik\LaravelSteamAuth\SteamInfo could not be converted to string

http://image.prntscr.com/image/22865767ec6040df8297df98772eeb24.jpeg

I can provide other info if you wish

cordially

**Comment by Yorkii** [comment]
Looks like magic method __get of Fluent isn't even called. Just tested it on PHP 7.0. However you can get attributes of SteamInfo this way `$steamInfo->get('steamID64')`.

**Comment by ImChip** [comment]
Hi @Yorkii 

Thanks its work :)

**Comment by psych0path1337** [comment]
@Yorkii could you help me with my problem?
I have the same but ErrorException in helpers.php line 747
[https://github.com/invisnik/laravel-steam-auth/issues/48]#148(url)
