### ISSUE TITLE
Get returned to Steamlogin Page

### ISSUE THREAD

**Issue by ReptoxX** [invisnik/laravel-steam-auth#42]
Hello,

i am facing an issue, where i login into steam and then when i normally gets redirected to my page, i get redirected to steam without any error message.
I checked all issues before and i am sure that my "redirect_url" is the same as $steam->validate().
So basically "validate()" is returning false all the time.

Regards ReptoxX

**Comment by xJoeyv** [comment]
Yea I have the same issue!

**Comment by sultanselim94** [comment]
I have the same issue too. Can someone tell what the problem is?

**Comment by xJoeyv** [comment]
I wrote now a own service class for Steam Login and used Live Facades in Laravel 5.4 to make use of them.

**Comment by ReptoxX** [comment]
will check it out, thanks.

**Comment by xJoeyv** [comment]
@ReptoxX Yes I plan publish the test version I have wrote for my gaming community. Im setting up the repo and will publish it soon. Just follow and keep track on my github.

**Comment by timetorock** [comment]
@ReptoxX , check if you have installed Guzzle. This library use it to make POST request.

Also, can you debug laravel-steam-auth\src\SteamAuth.php@validate() method? Check some variables to be sure they are not empty. Like $params, $response, $results.

Also be sure you've inserted `Config::get('steam-auth.api_key')`. Without it will return false for sure.

**Comment by ReptoxX** [comment]
Somehow it works and i dont know what happend.
