### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by burbakov1** [invisnik/laravel-steam-auth#46]
Opened site at localhost. Config:

`<?php

return [

    /*
     * Redirect URL after login
     */
    'redirect_url' => '/login',
    /*
     *  API Key (http://steamcommunity.com/dev/apikey)
     */
    'api_key' => 'A6B12375521B6D6B5066EFFB2E79F02C',
    /*
     * Is using https?
     */
    'https' => false
];`

Error screenshot: https://gyazo.com/0c0e987585b6566fed834505382ea468

**Comment by Rexeh** [comment]
This is a local configuration issue.

Point your php.ini to the local cert on the curlhax website.

**Comment by burbakov1** [comment]
Thank's.
