### ISSUE TITLE
Steam Auth not working because of double encoded URLs

### ISSUE THREAD

**Issue by Mechtecs** [invisnik/laravel-steam-auth#47]
I dont know why, but for whatever reason i get a login request from steam with a double encoded URL.

**Comment by Mechtecs** [comment]
My hotfix for this bug:
`public function __construct(Request $request)
    {
        $this->request = $request;
        $parameters = $this->request->all();
        foreach($this->request->request->all() as $k => $v) {
                $this->request->request->set($k, urldecode($v));
        }
        $this->authUrl = $this->buildUrl(url(Config::get('steam-auth.redirect_url'), [],
            Config::get('steam-auth.https')));
        $this->guzzleClient  = new GuzzleClient;
    }`

**Comment by MypowerHD** [comment]
in witch file do you make the Hotfix?! @Mechtecs

**Comment by Mechtecs** [comment]
SteamAuth.php @MypowerHD
