### ISSUE TITLE
Laravel steam login trouble

### ISSUE THREAD

**Issue by psych0path1337** [invisnik/laravel-steam-auth#48]
Hello, 

Today got a trouble on my web site, where i have a steam login from Laravel.

Got this problem: ErrorException in helpers.php line 747:
Object of class Invisnik\LaravelSteamAuth\SteamInfo could not be converted to string

Can someone help me with it please?

![hutde5q](https://cloud.githubusercontent.com/assets/26173870/23568767/c16be9be-0064-11e7-9843-23cd51ecc383.png)

**Comment by Yorkii** [comment]
It's not problem of library. You try to use object as bind in your query to database while selecting by `steamid`.

**Comment by psych0path1337** [comment]
@Yorkii have any solution for this? or what should i do to fix it?

**Comment by chriskonnertz** [comment]
@Yorkii Hi, this was a problem with third-party software and indeed was not an issue of the Steam auth library. So this issue here can be closed. :)
