### ISSUE TITLE
How to setup laravel-steam-auth in Laravel 5.4?

### ISSUE THREAD

**Issue by MiloslavKrejza** [invisnik/laravel-steam-auth#50]
Hello, i would love to ask how can i setup this in Laravel 5.4 i am having problem with routes. And with Auth forled.

**Comment by MiloslavKrejza** [comment]
I do not have AuthController under /Auth folder, what shall i do?﻿

**Comment by olicool11** [comment]
To generate the AuthController I ran
`php artisan make:controller Auth/AuthController` 

From there you can paste the code from the README. I also added a logout function which was simply;
```
public function logout(){
        Auth::logout();
        return redirect('/');
    }
```

For my routes file I then call these functions with;
```
Route::get('/login', 'AuthController@login');
Route::get('/logout', 'AuthController@logout');
```
