### ISSUE TITLE
What causing the login time to be long?

### ISSUE THREAD

**Issue by JakoMakoxx1** [invisnik/laravel-steam-auth#51]
Hey there! , for some reason the time that takes to login to my site is much longer then other sites ,
it takes sometimes around 10 seconds while other sites do it in 1 or sometimes even less

**Comment by ATomIK** [comment]
curling steam can take a bit depending on how good your machine is

**Comment by JakoMakoxx1** [comment]
I dont think the machine is bad - this what i use
https://www.soyoustart.com/us/offers/e5-sat-2-32.xml

**Comment by ATomIK** [comment]
that or latency. has nothing to do with invisnik's script.

**Comment by aim1909** [comment]
There are certain times when it takes a couple of seconds. That is just Steam being overloaded. However, most of the time, the login validation takes about 500ms over here - even on micro instances.
