### ISSUE TITLE
error bcsub()

### ISSUE THREAD

**Issue by Vova78rus** [invisnik/laravel-steam-auth#55]
Hi, can you help me with this error?
After log in in steam, i'm redirected to 
`/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198036284814&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198036284814&openid.return_to=https%3A%2F%2Fcsdrop.pro%2Flogin&openid.response_nonce=2017-05-15T17%3A24%3A15Zd7RzSF%2BMsGZndfs3yV7VM4jn7ew%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=%2BXVeEXu78RsV115KU62BGLmWdzI%3D`
and get this error:
http://prntscr.com/f85tc9

**Comment by invisnik** [comment]
Hello.
You need to enable php bcmath extension.

**Comment by Gummibeer** [comment]
If this is a requirement it should be in the `composer.json` and if you want in the readme.

**Comment by invisnik** [comment]
Fixed 9ce40b4
