### ISSUE TITLE
Wasn't able to get the logout function working...

### ISSUE THREAD

**Issue by Dreamborg** [invisnik/laravel-steam-auth#59]
Wasn't able to get the logout function working with the README's:
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

This was done on a fresh install of Laravel.

I was able to get it to work using a get request instead.

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

**Comment by invisnik** [comment]
For logout better use `post` method.
For example:
```blade
<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
{{ csrf_field() }}
</form>
```
