### ISSUE TITLE
Proxy for Auth

### ISSUE THREAD

**Issue by BlackOnix** [invisnik/laravel-steam-auth#65]
Hello. How can i use Proxy for Auth?
I get the following errors:
1. cURL error 7: Failed to connect to steamcommunity.com port 443: Connection timed out
2. cURL error 6: Could not resolve host: api.steampowered.com

**Comment by stevenklar** [comment]
Don't think this is possible right now.

As guzzle is private right now. (https://github.com/invisnik/laravel-steam-auth/blob/master/src/SteamAuth.php#L35)

If this variable could be protected, you could overwrite the class yourself and add your own guzzle implementation with proxy settings. (https://github.com/guzzle/guzzle/blob/master/src/Client.php#L171)
