### ISSUE TITLE
L5.5 not automatically adding to providers

### ISSUE THREAD

**Issue by kieran-s** [invisnik/laravel-steam-auth#67]
Running Laravel 5.5.9 via homestead.

Follow instructions to add to composer.json, run composer update (as lock file exists, so install doesn't add), check providers under config->app.php and the provider has not been automatically added.

Not a major issue (just added the line manually), but thought I'd let you know either way.

**Comment by invisnik** [comment]
In Laravel 5.5, it is not necessary to add the provider class in config/app.php
The provider registers automatically
