### ISSUE TITLE
Use different domain for Steam authentication

### ISSUE THREAD

**Issue by GrandmaJam** [invisnik/laravel-steam-auth#68]
I am trying to make the openid.realm and openid.redirect_to different from the site's URL like csgoroll does. 

After I log in to the site via Steam it changes the URL to a long messy link: (https://pastebin.com/x0AFksTR)

config.php being used: https://pastebin.com/UXMrTZvA SteamAuth.php being used: https://pastebin.com/13EGqD0y.

I get that error after I press sign in on steam's log in page. It takes me back to the site but doesn't log me in and gives me that long messy link above.

I ONLY GET THIS ERROR WHEN I CHANGE THE REDIRECT TO URL. IF THE REDIRECT URL ISNT SET IN STEAMAUTH.PHP AND IS SET IN CONFIG.PHP IT DOESNT WORK FOR ME. Please help me, I hope I explained this well.

**Comment by GrandmaJam** [comment]
I need to change the openid.realm and openid.redirect_to. When I change the redirect_url in config.php it doesn't do anything. Please show me how to change this. My config: https://pastebin.com/JFtBen7X

**Comment by invisnik** [comment]
Redirect URL in the config is redirects to your controller method for log in.
And in this method you redirect user to the site page after log in.
Look [example](https://github.com/invisnik/laravel-steam-auth#usage-example)

**Comment by GrandmaJam** [comment]
How would i redirect them to Steam using a different domain for authentication? Then once they're authenticated send them back to the domain they were just on before authentication.

**Comment by GrandmaJam** [comment]
Do you know how I would do this?

**Comment by GrandmaJam** [comment]
? Is there any other way to chat with you invisnik? Want to get this solved today. I can pay you to do it for me.

**Comment by invisnik** [comment]
It is not the package`s issue.
Try to link the new domain, and through him to perform authentication, and then redirected to the old domain.

**Comment by GrandmaJam** [comment]
I understand that it's not your package's issue. But I want to get this setup for my site. Can I pay you to do it for me? or do you know anyone that would do it for me?
