### ISSUE TITLE
API key?

### ISSUE THREAD

**Issue by grupp3pvt15** [invisnik/laravel-steam-auth#7]
Is no API key needed? Also can other steamuser information be accessed with with plugin?

**Comment by invisnik** [comment]
For current version API key is not need. Perhaps in the future versions it will be release.

**Comment by grupp3pvt15** [comment]
That would be awesome! Especially if you could implement similar user variables like https://github.com/SmItH197/SteamAuthentication or some methods for like checking user's inventories etc. Anyways, thanks for the reply!
