### ISSUE TITLE
Getting 429: Too Many Requests

### ISSUE THREAD

**Issue by toofast1** [invisnik/laravel-steam-auth#74]
Hello,

Suddenly I am unable to auth through steam on my application anymore. I get this error:
`Client error: GET http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=C63F514B1FE910EC7726D80971F60xxx&steamids=76561197987844xxx resulted in a `429 Too Many Requests` response: <html> <head> <title>429 Too Many Requests</title> </head> <body> <h1>Too Many Requests</h1> </body> </html>`

I think that Steam has blocked the IP address of my VPS and it's been almost 1 day since I am unable to log in and yet not working. Can this block be permanent?

Should I try to place a delay to the GET request? If so, how can I do this?

**Comment by dhurley94** [comment]
Instead of placing a delay you could use a proxy, but you would need multiple web api keys in order to do that. Alternatively, your code may be syncing with Valve's server's to often. You may want to review the auth modules in detail.

**Comment by Harsukh21** [comment]
this API error many time getting during if so many API request is getting in your application.
if you wanna get resolve this error message in your Laravel API then please follow this step
step - 1 : open your `app/Http/Kernel.php` file and comment bellow line
`protected $middlewareGroups = [ `
        `...`
   ` 'api' => [`
       ` // 'throttle:60,1',`
   ` ],`
`];`
