### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by ryandeming** [invisnik/laravel-steam-auth#76]
Keep getting this error, did setup as instructed through the readme. 
https is false. 
api key is in the .env
added steamid, avatar, and username to user table, creation function, and model.
set up routes and redirects.

Looking for some help. 

http://prntscr.com/irnmzb

**Comment by invisnik** [comment]
Look #46
