### ISSUE TITLE
Undefined offset: 1 in /vendor/invisnik/laravel-steam-auth/src/SteamAuth.php:95

### ISSUE THREAD

**Issue by devmigi** [invisnik/laravel-steam-auth#78]
Hi,
Since today morning i'm getting this error! Anyone facing same issue?

**Comment by WuXeR** [comment]
I am getting the same error

**Comment by WuXeR** [comment]
It might be openid being down or smt. since I'm getting this since this morning too ? 
Need help!!!!

**Comment by devmigi** [comment]
Found the solution,
on line /vendor/invisnik/laravel-steam-auth/src/SteamAuth.php:94,  replacing 
preg_match("#^http://steamcommunity.com/openid/id/([0-9]{17,25})#", $get['openid_claimed_id'], $matches);
with
preg_match("#^https://steamcommunity.com/openid/id/([0-9]{17,25})#", $get['openid_claimed_id'], $matches);
fixed it.

i was using v2.2.0

**Comment by WuXeR** [comment]
Yep this worked. what a legend thx!!
