### ISSUE TITLE
parseSteamID error

### ISSUE THREAD

**Issue by orlyapps** [invisnik/laravel-steam-auth#79]
Steam changed this url "http://steamcommunity.com/openid/id/" to https.
"https://steamcommunity.com/openid/id/"

`    public function parseSteamID()
    {
        preg_match("#^https://steamcommunity.com/openid/id/([0-9]{17,25})#", $this->request->get('openid_claimed_id'), $matches);
        $this->steamId = is_numeric($matches[1]) ? $matches[1] : 0;
    }`

**Comment by invisnik** [comment]
Fixed in #77 
Update your package to v3.2.1
