### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by Yorkii** [invisnik/laravel-steam-auth#80]
So today it stopped working with following exception:

> Undefined offset: 1 in /vendor/invisnik/laravel-steam-auth/src/SteamAuth.php:205

You should change regular expression to:
`#^https?://steamcommunity.com/openid/id/([0-9]{17,25})#`

Since it doesn't work with https protocol.

**Comment by cat24max** [comment]
Why is this issue closed?
