### ISSUE TITLE
cUrl error 60 on localhost without https after new update

### ISSUE THREAD

**Issue by eric101110** [invisnik/laravel-steam-auth#83]
RequestException in CurlFactory.php line 186:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I set https to false but I still get the error.

**Comment by Gummibeer** [comment]
https://stackoverflow.com/a/21114601/4907524

**Comment by eric101110** [comment]
Worked, thanks I appreciate it!
