### ISSUE TITLE
[FR] Variable redirect_url

### ISSUE THREAD

**Issue by stemis** [invisnik/laravel-steam-auth#88]
Hi,

Can you make the `redirect_url` configurable?

I want to set the `redirect_url` when issuing the `return $steamAuth->redirect();`

When the laravel application serves multiple front-end applications, this can be quite handy!
This way I can make it return to say `domain.com/auth/handle?application=front-end-1`

That way, my `handle()` method knows where to send the user to next.

Thank you

**Comment by invisnik** [comment]
You can use `setRedirectUrl` method.
https://github.com/invisnik/laravel-steam-auth/blob/fa54638fbcf7dc8b8fdb65c16ae7e7ba47b53620/src/SteamAuth.php#L190-L200

**Comment by Gummibeer** [comment]
Was added in #56

**Comment by Gummibeer** [comment]
@invisnik cause my comment hadn't any follow-up change I will make this method chainable tomorrow.

**Comment by stemis** [comment]
I overlooked that function, sorry about that, this is exactly what I need, thanks!
