### ISSUE TITLE
Drop PHP5 support

### ISSUE THREAD

**Issue by Gummibeer** [invisnik/laravel-steam-auth#89]
PHP 5 ist out of support for more than one year and looses security support end of this year.
http://php.net/supported-versions.php
PHP 7 adds a lot of new features, is faster and we can't stay with PHP 5 forever. 😉

I would send a PR that brings this library to PHP 7.

**Comment by kanalumaddela** [comment]
What would you change that *"brings this library to PHP 7"* ???

Change
```php
$steamID = isset($data['steamid']) ? $data['steamid'] : null;
```
to
```php
$steamID = $data['steamid'] ?? null;
```
😂

Bumping up the minimum PHP version makes no sense if all you're trying to do is get people on PHP7. It'd be helpful if you actually provided examples or at least some code utilizing PHP7 that warrants being good enough to make the new minimum.

**Comment by kanalumaddela** [comment]
Listing PHP7 features doesn't mean anything. How does type hinting benefit this lib? All it does is improve code quality, it doesn't increase its performance whatsoever. Same applies to return type declarations.

**Comment by Gummibeer** [comment]
And code quality, type security and for sure performance aren't reasons to go with the time!? 😉
Everyone that stays with PHP5 can still use older versions. But everyone else benefits. Also by up2date dependencies which isn't possible atm.
