### ISSUE TITLE
Working state ? Documentation ?

### ISSUE THREAD

**Issue by radiumx3** [invisnik/laravel-steam-auth#9]
Is the snippet provided in the readme supposed to work ?

Entering a login loop with this snippet, and can't get any data in the $steam object after login on the steam webpage.

A clear documentation on how all this work wouldn't be too much ..

**Comment by ryantology** [comment]
Maybe you would like to give some specs on your project and we can just code it for you.

**Comment by radiumx3** [comment]
@ryantology U Stalker !

**Comment by KriiV** [comment]
It appears that the example code in the Readme creates a redirect loop after the user tries to login. That then doesn't allow login to fully happen and doesn't give access to user details. 

I hacked a solution using a session variable and checking for login before redirect to steam domain but there needs to be a better solution.

**Comment by invisnik** [comment]
I'm updated documentation. I hope i explained clear how use this :)

**Comment by radiumx3** [comment]
Thanks
