### ISSUE TITLE
SteamID conversion

### ISSUE THREAD

**Issue by Gummibeer** [invisnik/laravel-steam-auth#90]
Cause of the fact that the `bcmath` extension is only required cause of the steamID64 to steamID conversion.
Except of the fact that this conversion is possible without `bcmath` I think that this isn't needed and if it is the concept is incomplete.

1. This steamID isn't needed for auth
2. There are three steamID types, just offer two makes no sense

My main goal is to drop the `bcmath` extension.
@invisnik do you want to ... ?
1. keep the conversion but drop bcmath
2. drop bcmath and add the third steamID
3. drop the conversion in total (breaking)

**Comment by invisnik** [comment]
Let's leave the discussion open for a while and see what other people think.
I think we can drop the conversion in total.

**Comment by Gummibeer** [comment]
I would drop it in favor of packages that focus on this like https://github.com/xPaw/SteamID.php

Cause this package doesn't need it and for auth it isn't needed this isn't a task of this package.
