### ISSUE TITLE
HTTP to HTTPS 

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [invisnik/laravel-steam-auth#99]
Steam now requires that all requests made to their API endpoint needs to be made via HTTPS. I had a lot of issues by not having making calls to HTTPS. I think a change is needed in all files and remove the option of "Is using HTTPS" in the config file

**Comment by Gummibeer** [comment]
The option in the config doesn't change the requests to steam but if your callback is called via https or http.
And this is the only point where I see a `http` request https://github.com/invisnik/laravel-steam-auth/blob/master/src/SteamAuth.php#L46 feel free to fix it. 😉 The parser was fixed in #77
